version: "3.7"
services: 
    app:
        image: node:lts
        command: sh -c "npm install && npm run dev"
        # command: sh -c "npm install && npm run build && npm run start"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: facebook

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: facebook